name: awesome_dio_interceptor
description: A simple dio log interceptor (mainly inspired by the built-in dio LogInterceptor), which has coloring features and json formatting so you can have a better readable output.
version: 1.2.0
homepage: https://github.com/devmuaz/awesome_dio_interceptor

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  dio: ^5.4.0
  colorize: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
